#!/bin/bash

#CONFIG {{{
export VIDEO_FORMAT=NTSC # "PAL" || "NTSC" - DvdAuthor 7 and up needs this
ASPECT_RATIO="16:9"
INPUT_PATH=$1
INPUT_FILE=$(basename "$INPUT_PATH")
TMP_PATH=$(mktemp -d --suffix=-video2dvd)
ISO_FILE="$TMP_PATH/dvd.iso"
MPG_FILE="$TMP_PATH/$INPUT_FILE.mpg"
DVD_PATH="$TMP_PATH/dvd"
DVD_XML="$TMP_PATH/dvd.xml"
#}}}

function print_paths() {
    echo "***********************"
    echo "INPUT_PATH: $INPUT_PATH"
    echo "INPUT_FILE: $INPUT_FILE"
    echo "TMP_PATH: $TMP_PATH"
    echo "ISO_FILE: $ISO_FILE"
    echo "MPG_FILE: $MPG_FILE"
    echo "DVD_PATH: $DVD_PATH"
    echo "***********************"
}

function depend_check() {
    # Check for dependencies
    missing=0
    dependencies=( "ffmpeg" "dvdauthor" "genisoimage" )
    for command in ${dependencies[@]}
    do
        if ! command -v $command &>/dev/null
        then
            echo "$command not found"
            missing=1
        fi
    done
    return missing
}

function emphasise() {
    echo ""
    echo "********** $1 **********"
    echo ""
}

function create_mpg() {
    emphasise "Converting AVI to MPG"
    ffmpeg -i "$INPUT_PATH" -y -target ${VIDEO_FORMAT,,}-dvd -aspect $ASPECT_RATIO "$MPG_FILE"
    if [ $? != 0 ]
    then
        print_paths
        emphasise "Conversion failed"
        exit
    fi    
}

function create_xml() {
    emphasise "Creating XML file"
    echo "<dvdauthor>
    <vmgm />
    <titleset>
    <titles>
    <pgc>" > $DVD_XML
    echo "<vob file=\"$MPG_FILE\" />" >> $DVD_XML
    echo "</pgc>
    </titles>
    </titleset>
    </dvdauthor>" >> $DVD_XML
}

function create_dvd() {
    emphasise "Creating DVD contents"
    dvdauthor -o $DVD_PATH -x $DVD_XML
    if [ $? != 0 ]
    then
        print_paths
        emphasise "DVD Creation failed"
        exit
    fi    
}

function create_iso() {
    emphasise "Creating ISO image"
    genisoimage -dvd-video -o $ISO_FILE $DVD_PATH
    if [ $? != 0 ]
    then
        print_paths
        emphasise "ISO Creation failed"
        exit
    fi    
}

if [ $# -lt 1 ]
then
    echo "Usage: $0 <video file.avi|mpg|mkv|mp4|etc>"
    exit
fi

if [ depend_check = 1 ]
then
    echo "Please install the missing applications and try again"
    exit
fi

# Check the files exists
if [ ! -e $INPUT_PATH ]
then
    echo "File $INPUT_PATH not found"
    exit
fi

create_mpg
create_xml 
create_dvd
create_iso

emphasise "Success: $ISO_FILE image created"
