#!/bin/bash

# "PAL" || "NTSC"
export VIDEO_FORMAT=NTSC # DvdAuthor 7 and up needs this
ASPECT_RATIO="16:9"
INPUT_PATH=$1
INPUT_FILE=$(basename "$INPUT_PATH")
TMP_PATH=$(mktemp -d --suffix=-video2dvd)
ISO_FILE="$TMP_PATH/dvd.iso"
MPG_FILE="$TMP_PATH/$INPUT_FILE.mpg"
DVD_PATH="$TMP_PATH/dvd"
DVD_XML="$TMP_PATH/dvd.xml"

function print_paths() {
    echo "***********************"
    echo "INPUT_PATH: $INPUT_PATH"
    echo "INPUT_FILE: $INPUT_FILE"
    echo "TMP_PATH: $TMP_PATH"
    echo "ISO_FILE: $ISO_FILE"
    echo "MPG_FILE: $MPG_FILE"
    echo "DVD_PATH: $DVD_PATH"
    echo "***********************"
}

function depend_check() {
    # Check for dependencies
    missing=0
    dependencies=( "ffmpeg" "dvdauthor" "genisoimage" )
    for command in ${dependencies[@]}
    do
        if ! command -v $command &>/dev/null
        then
            echo "$command not found"
            missing=1
        fi
    done
    return missing
}

if [ $# -lt 1 ]
then
    echo "Usage: $0 <video file>"
    exit
fi

if [ depend_check = 1 ]
then
    echo "Please install the missing applications and try again"
    exit
fi

function emphasise() {
    echo ""
    echo "********** $1 **********"
    echo ""
}

# Check the files exists
if [ ! -e $INPUT_PATH ]
then
    echo "File $INPUT_PATH not found"
    exit
fi

emphasise "Converting AVI to MPG"

ffmpeg -i "$INPUT_PATH" -y -target ${VIDEO_FORMAT,,}-dvd -aspect $ASPECT_RATIO "$MPG_FILE"
if [ $? != 0 ]
then
    print_paths
    emphasise "Conversion failed"
    exit
fi

emphasise "Creating XML file"

echo "<dvdauthor>
<vmgm />
<titleset>
<titles>
<pgc>" > $DVD_XML

echo "<vob file=\"$MPG_FILE\" />" >> $DVD_XML

echo "</pgc>
</titles>
</titleset>
</dvdauthor>" >> $DVD_XML

emphasise "Creating DVD contents"

dvdauthor -o $DVD_PATH -x $DVD_XML

if [ $? != 0 ]
then
    print_paths
    emphasise "DVD Creation failed"
    exit
fi

emphasise "Creating ISO image"

genisoimage -dvd-video -o $ISO_FILE $DVD_PATH

if [ $? != 0 ]
then
    print_paths
    emphasise "ISO Creation failed"
    exit
fi

# Everything passed. Cleanup
#rm -f "$TMP_PATH/$INPUT_PATH.mpg"
#rm -rf dvd/
#rm -f dvd.xml

emphasise "Success: $ISO_FILE image created"
